services:
  ui:
    image: my-nginx
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  db:
    image: postgres:latest
    container_name: kv-postgres
    env_file:
      - ./api/.env
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data
