services:
  ui-legacy:
    image: kv-ui
    build:
      context: ./ui-legacy
      dockerfile: dockerfile
    ports:
      - "8080:80"
  api:
    image: kv-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - ./api/.env
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data
